import type { Metadata } from "next";
import { Geist, Geist_Mono, Newsreader } from "next/font/google";
import { Header } from "@/components/layout/Header";
import "./globals.css";

// ─── Body font: clean geometric sans-serif ──────────────────────────────────
// Geist Sans is the primary reading/UI font.
// variable: "--font-sans" exposes it as a CSS variable that globals.css and
// Tailwind's @theme block can consume with `font-sans`.
const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

// ─── Display/heading font: expressive editorial serif ────────────────────────
// Newsreader gives us that high-contrast Vox/magazine editorial quality.
// We load both roman and italic, with optical sizing enabled via font-size.
// variable: "--font-serif" — used for all h1–h3 headings and pull-quotes.
const newsreader = Newsreader({
  variable: "--font-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

// ─── Monospace font: issue stamps, dates, code, badges ───────────────────────
// Used for metadata elements like "VOL. 01 // 2026", date tags, and code blocks.
const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

// ─── Site-wide SEO metadata ──────────────────────────────────────────────────
// Next.js exports this object and injects it into <head> automatically.
// No more manually writing <title> or <meta> tags in HTML files!
export const metadata: Metadata = {
  title: {
    default: "Mnasie — Developer & Designer",
    // %s will be replaced by the page's own title, e.g. "Blog | Mnasie"
    template: "%s | Mnasie",
  },
  description:
    "Personal portfolio and technical blog by Mnasie. Building things on the web.",
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Mnasie",
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon.png", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: "/apple-icon.png",
  },
};

// ─── Root Layout ─────────────────────────────────────────────────────────────
// This component wraps EVERY page on the site. Think of it as your master
// HTML template — the equivalent of copy-pasting a <nav> and <footer> into
// every HTML page, except here you define it once and Next.js handles the rest.
//
// LayoutProps<"/"> is a type auto-generated by Next.js that describes what
// props this layout receives (mainly {children} — the page content).
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // We inject the three CSS variable names as classes on <html>.
      // This is how next/font works: it creates scoped CSS variable definitions
      // that are only active when these class names are present on an ancestor.
      className={`${geistSans.variable} ${newsreader.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        {/* Header lives here in the layout so it appears on EVERY page */}
        {/* without needing to import it in each individual page file.  */}
        <Header />
        <main className="flex flex-col flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
